### ISSUE TITLE
Missing windows dependency

### ISSUE THREAD

**Issue by spencer-cdw** [merative/spm-middleware#130]
Version: 1.9.1

When running on RHEL 8, the playbook expects windows collection to be installed. If the collection is not installed, users will get this error. 

```
TASK [Install IBM Installation Manager] ****************************************
ERROR! couldn't resolve module/action 'win_stat'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/runner/.ansible/collections/ansible_collections/merative/spm_middleware/roles/iim/tasks/main.yml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Check if IIM is installed (Windows)
  ^ here
```

## Steps to reproduce
Add requrements.txt

```
  - name: merative.spm_middleware
    version: "1.9.1"
    source: https://github.com/merative/spm-middleware
    type: git
```

Attempt to install iim
```
- name: Install IBM Installation Manager
  ansible.builtin.include_role:
    name: merative.spm_middleware.iim
  vars:
    iim_agent_version: "1.9.1001.20240227_0018"
    iim_install_path: "/opt/oms/softwares/IIM"
```

The playbook should add a dependency on the windows role/collection.
