### ISSUE TITLE
Playbook always attempts to download java from http

### ISSUE THREAD

**Issue by spencer-cdw** [merative/spm-middleware#134]
Related to https://github.com/merative/spm-middleware/issues/132

## Problem 

The playbook always attempts to download java from `download_url` when `jdk_installation_way` is defined. 

The playbook doesn't handle the use case where a user is attempting to install from a network mount instead of https. 

## Steps to Reproduce

```
- name: Install Liberty
  ansible.builtin.include_role:
    name: merative.spm_middleware.liberty 
  vars:
    liberty_version: "25.0.0.3-JDK21"
    liberty_install_path: "/opt/oms/softwares/WASLIBERTY_ND/WAS"
    liberty_default_heapsize: "1024m"
    liberty_enable_verbose_gc: false
    liberty_extra_jvm_options: []
    iim_install_path: "/opt/oms/softwares/IIM"
    # download_url: ""
    # download_header: ""
    liberty_installers_path: "/mnt/foobar/was.repo.16002.liberty.nd.zip"
    liberty_fp_path: "/mnt/foobar/25.0.0.3-WS-LIBERTY-ND-FP.zip"
    # liberty_java_zip_path: "/mnt/foobar/sdk.repo.8030.java8.linux.zip"
```

## Output

Notice that Both `Install Java (iim way)` and `Download JDK (unzip way)` are skipped. 
This results in the error `Source /tmp/jdk.zip does not exist`

```
TASK [merative.spm_middleware.liberty : Install Base version] ******************
skipping: [t1raoms005.ssc.tsc] => {"changed": false, "false_condition": "not iim_info.base_installed", "skip_reason": "Conditional result was False"}
TASK [merative.spm_middleware.liberty : Install Fixpack version] ***************
skipping: [t1raoms005.ssc.tsc] => {"changed": false, "false_condition": "not iim_info.exact_installed", "skip_reason": "Conditional result was False"}
TASK [merative.spm_middleware.liberty : Install Java (iim way)] ****************
skipping: [t1raoms005.ssc.tsc] => {"changed": false, "false_condition": "(not iim_info.exact_installed) and ( jdk_installation_way is undefined )", "skip_reason": "Conditional result was False"}
TASK [merative.spm_middleware.liberty : Download JDK (unzip way)] **************
skipping: [t1raoms005.ssc.tsc] => {"changed": false, "false_condition": "(download_url is defined) and ( jdk_installation_way is defined )", "skip_reason": "Conditional result was False"}
TASK [merative.spm_middleware.liberty : Prepare Open JDK Folder (unzip way)] ***
changed: [t1raoms005.ssc.tsc] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/opt/oms/softwares/WASLIBERTY_ND/WAS/java/21.0", "secontext": "unconfined_u:object_r:unlabeled_t:s0", "size": 6, "state": "directory", "uid": 0}
TASK [merative.spm_middleware.liberty : Install Java (unzip way)] **************
fatal: [t1raoms005.ssc.tsc]: FAILED! => {"changed": false, "msg": "Source '/tmp/jdk.zip' does not exist"}
```

## Cause

The playbook assumes there are only 2 ways to install java. 
1. IIM
2. Downloading JDK

This makes it incompatible with IIM and Liberty which can both be installed from a local path. 

```yaml
- name: Install Java (iim way)
  include_tasks: fixpack_install.yml
  vars:
    liberty_fp_path: "{{ liberty_java_zip_path }}"
    pack_id: "{{ liberty_java_pid }}"
  when: (not iim_info.exact_installed) and ( jdk_installation_way is undefined )

- name: Download JDK (unzip way)
  get_url:
    dest: /tmp/jdk.zip
    url: "{{ download_url }}/{{ liberty_java_zip_path }}"
    headers: "{{ download_header }}"
  when: (download_url is defined) and ( jdk_installation_way is defined )
```

## Purposed solution

Add a 3rd installation method to fetch /tmp/jdk.zip when `jdk_installation_way` is defined and `download_url` is not defined

```
- name: Copy JDK locally (unzip way)
  copy:
    src: "{{ ????? }}" 
    dest: /tmp/jdk.zip
    remote_src: yes
  when: (not download_url is defined) and (jdk_installation_way is defined ) 
```
