### ISSUE TITLE
Release.yaml error when creating GitHub Release

### ISSUE THREAD

**Issue by ourboy** [merative/spm-middleware#39]
There is an error in the following code block in release.yaml

```
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ env.collection_namespace }}-${{ env.collection_name }}-${{ env.version }}.tar.gz

```

the following error is thrown

```

Run marvinpinto/action-automatic-releases@latest
Initializing the Automatic Releases action
Determining release tags
  Error: The parameter "automatic_release_tag" was not set and this does not appear to be a GitHub tag event. (Event: refs/heads/main)
  (node:1879) UnhandledPromiseRejectionWarning: Error: The parameter "automatic_release_tag" was not set and this does not appear to be a GitHub tag event. (Event: refs/heads/main)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:215307
      at Generator.next (<anonymous>)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:212987
      at new Promise (<anonymous>)
      at s (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:212732)
      at Object.t.main (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:214262)
      at Object.<anonymous> (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:212105)
      at r (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:124)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:923
      at Object.<anonymous> (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:933)
  (node:1879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:1879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

at the moment, Github release can be ran manually as a workaround
